language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy

install:
  - travis_retry pip install -q mock nose PyHamcrest
  - python setup.py -q install
script:
  - python --version
  - nosetests
  - behave -f progress --junit --tags=~@xfail features/
  - behave -f progress --junit --tags=~@xfail tools/test-features/
  - behave -f progress --junit --tags=~@xfail issue.features/
