language: python
sudo: false
python:
  - "3.5"
  - "2.7"
  - "2.6"
  - "pypy"
  - "nightly"
  - "3.4"
  - "3.3"

# NOW SUPPORTED: "3.5" => python 3.5.2 (>= 3.5.1)
# NOTE: Python 3.5.0 is broken (for some tests).

# DISABLED: - "nightly"
# -- AVOID:  python: "3.5" => python 3.5.0
# Seems to have a problem with unit tests in exception traceback.
# Behaviour is fixed in python 3.5.1

# -- TEST-BALLON: Check if Python 3.6 is actually Python 3.5.1 or newer
matrix:
  allow_failures:
    - python: "nightly"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -q mock nose PyHamcrest
  - travis_retry pip install -q -U pytest
  - python setup.py -q install

script:
  - python --version
  - py.test test tests
  - behave -f progress --junit features/
  - behave -f progress --junit tools/test-features/
  - behave -f progress --junit issue.features/

after_failure:
  - echo "FAILURE DETAILS (from XML reports):"
  - bin/behave.junit_filter.py --status=failed reports

# -- ALTERNATIVE:
#  egrep -L 'errors="0"|failures="0"' reports/*.xml | xargs -t cat

# -- USE: New container-based infrastructure for faster startup.
#    http://docs.travis-ci.com/user/workers/container-based-infrastructure/
#
# SEE ALSO:
#   http://lint.travis-ci.org
#   http://docs.travis-ci.com/user/caching/
#   http://docs.travis-ci.com/user/multi-os/  (Linux, MACOSX)
