# =============================================================================
# CI-SERVER CONFIGURATION: behave
# =============================================================================
# OS: Windows
# SEE ALSO:
#   * http://www.appveyor.com/docs/build-configuration
#   * http://www.appveyor.com/docs/installed-software#python
#   * http://www.appveyor.com/docs/appveyor-yml
# =============================================================================
# https://bootstrap.pypa.io/get-pip.py
# MAYBE: python2.6:    - choco install pip

version: 1.2.6.dev0.{build}-{branch}
clone_folder: C:\projects\behave.ci
# clone_depth:  2
# shallow_clone: true

environment:
  PYTHONPATH: ".;%CD%"
  BEHAVE_ROOTDIR_PREFIX: "C:"
  matrix:
    - PYTHON_DIR:  C:\Python27
      BEHAVE_ROOTDIR_PREFIX: "c:"
    - PYTHON_DIR:  C:\Python35

# -- TEMPORARILY DISABLED: environment matrix:
#    - PYTHON_DIR:  C:\Python34
#    - PYTHON_DIR:  C:\Python26
#    - PYTHON_DIR:  C:\Python33
#    - PYTHON_DIR:  C:\Python26-x64
#    - PYTHON_DIR:  C:\Python27-x64
#    - PYTHON_DIR:  C:\Python33-x64
#    - PYTHON_DIR:  C:\Python34-x64
#    - PYTHON_DIR:  C:\Python35-x64

init:
    - "echo TESTING-WITH %PYTHON_DIR%"

# -- TEMPORARILY DISABLED: Python variants discovery
#    - @echo INSTALLED PYTHON_DIR VERSIONS
#    - @dir C:\Python*
#    - path

install:
    - "%PYTHON_DIR%\\python.exe -m pip install pytest mock PyHamcrest nose"
    - "%PYTHON_DIR%\\python.exe -m pip install ."

build: off
test_script:
    - "%PYTHON_DIR%\\Scripts\\py.test.exe test tests"
    - "%PYTHON_DIR%\\Scripts\\behave -f progress3 --junit issue.features"

# -- TEMPORARILY DISABLED:
#    - "%PYTHON_DIR%\\Scripts\\behave.exe -f progress3 --junit features"
